export const buttonNames = [
  "book appointment",
  "schedule appointment",
  "book doctor appointment",
  "schedule doctor appointment",
  "book consultation",
  "schedule consultation",
  "book now",
  "schedule now",
  "book online",
  "schedule online",
  "request appointment",
  "request consultation",
  "reserve appointment",
  "reserve consultation",
  "find doctor",
  "find appointment",
  "book visit",
  "schedule visit",
  "book checkup",
  "schedule checkup",
  "book doctor online",
  "schedule doctor online",
  "book health checkup",
  "schedule health checkup",
  "book medical appointment",
  "schedule medical appointment",
  "book clinic appointment",
  "schedule clinic appointment",
  "book specialist appointment",
  "schedule specialist appointment",
  "make an appointment",
  "book a visit",
  "book meeting",
  "book session",
  "book an appoinment",
  "book appointment",
  "schedule appointment",
  "book now",
  "schedule now",
  "reserve appointment",
  "make an appointment",
  "book a visit",
  "book consultation",
  "book meeting",
  "book session",
  "book a demo",
];
